### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by bleucitron** [bleucitron/pokesvelte#45]
## `01/01`
- [ ] espace manquant après `src`

**Comment by Rachad-Alabi-ADEKAMBI** [comment]
c'est dans quel fichier ? @bleucitron

**Comment by bleucitron** [comment]
`course/01_sveltekit_basics/01_structure.md`, comme le `01/01` le laisse supposer :p

**Comment by Rachad-Alabi-ADEKAMBI** [comment]
;(  c'est fait, le pull request est ouvert
